services:
  nextjs:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file:
      - ./app/.env
    ports:
      - "3000:3000"

    depends_on:
      - fastapi
      - postgres
    volumes:
      - ./app:/lingo/app
      - app_node_modules:/lingo/app/node_modules

  fastapi:
    container_name: service
    build:
      context: ./service
      dockerfile: Dockerfile
    env_file:
      - ./service/.env
    depends_on:
      - ollama
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./service:/lingo/service
  postgres:
    container_name: lingo-db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER_FILE:  /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB_FILE: /run/secrets/db_name
    ports:
     - "5432:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data
    secrets:
      - db_user
      - db_name
      - db_password

  ollama:
    container_name: ollama
    image: ollama/ollama:0.6.6
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  redis:
    container_name: lingo-redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

secrets:
  db_user:
    file: ./secrets/pg/db_user.txt
  db_name:
    file: ./secrets/pg/db_name.txt
  db_password:
    file: ./secrets/pg/db_password.txt

volumes:
  postgres_data:
  ollama_data:
