/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/tmQkBG9cuxt
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Sheet, SheetTrigger, SheetContent } from "@/components/ui/sheet"
import { Button } from "@/components/ui/button"

const hamburgerMenu = () => {
  return (
    <header className="fixed top-0 left-0 z-50 w-full bg-background shadow-sm">
      <div className="container flex h-16 items-center justify-between px-4 md:px-6">
        <Link href="#" className="flex items-center gap-2" prefetch={false}>
          <span className="sr-only">Acme Inc</span>
        </Link>
        <Sheet>
          <SheetTrigger asChild>
            <Button variant="outline" size="icon" className="rounded-full">
              <span className="sr-only">Toggle navigation menu</span>
            </Button>
          </SheetTrigger>
          <SheetContent side="right" className="bg-background">
            <div className="flex h-full flex-col justify-between">
              <nav className="flex flex-col gap-4 px-4 py-6 sm:px-6 sm:py-10">              
                <Link
                  href="#"
                  className="text-lg font-medium hover:underline hover:underline-offset-4"
                  prefetch={false}
                >
                  Services
                </Link>
                <Link
                  href="#"
                  className="text-lg font-medium hover:underline hover:underline-offset-4"
                  prefetch={false}
                >
                  Contact
                </Link>
              </nav>
              <div className="border-t px-4 py-6 sm:px-6 sm:py-10">
                <Button variant="outline" className="w-full">
                  Get Started
                </Button>
              </div>
            </div>
          </SheetContent>
        </Sheet>
      </div>
    </header>
  )
}
export default hamburgerMenu;
